In [ ]:
import numpy as np
array1 = np.array([1,2,3,4,5])
type(array1)
array1

numpy.ndarray

In [3]:
array2 = np.array([9,8,7,6,5])
array2

array([9, 8, 7, 6, 5])

In [4]:
array3 = array1 + array2
array3

array([10, 10, 10, 10, 10])

In [ ]:
#Create an empty array with 10 elements
np.empty((10,))

array([4.68511868e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       4.72176024e+257, 8.75413118e+169, 1.14195572e-071, 4.76181309e-090,
       9.84095898e-072, 5.18089433e-310])

In [ ]:
#The order: starting value of the sequence, the ending value of the sequence, the step size
np.arange(0.5,10,0.5)


array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
#Generate a sequence of evenly spaced numbers within a specified range
#50 elements by default
np.linspace(-3, 3)


array([-3.        , -2.87755102, -2.75510204, -2.63265306, -2.51020408,
       -2.3877551 , -2.26530612, -2.14285714, -2.02040816, -1.89795918,
       -1.7755102 , -1.65306122, -1.53061224, -1.40816327, -1.28571429,
       -1.16326531, -1.04081633, -0.91836735, -0.79591837, -0.67346939,
       -0.55102041, -0.42857143, -0.30612245, -0.18367347, -0.06122449,
        0.06122449,  0.18367347,  0.30612245,  0.42857143,  0.55102041,
        0.67346939,  0.79591837,  0.91836735,  1.04081633,  1.16326531,
        1.28571429,  1.40816327,  1.53061224,  1.65306122,  1.7755102 ,
        1.89795918,  2.02040816,  2.14285714,  2.26530612,  2.3877551 ,
        2.51020408,  2.63265306,  2.75510204,  2.87755102,  3.        ])